export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_ONE_ERROR = 'CLEAR_ONE_ERROR';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const SET_USER = 'SET_USER';
export const UNSET_USER = 'UNSET_USER';

export const CREATE_DAILY_START = 'CREATE_DAILY_START';
export const CREATE_DAILY_END = 'CREATE_DAILY_END';
export const GET_ALL_DAILIES_START = 'GET_ALL_DAILIES_START';
export const GET_ALL_DAILIES_END = 'GET_ALL_DAILIES_END';
export const GET_ALL_DAILIES_BY_TAG_START = 'GET_ALL_DAILIES_BY_TAG_START';
export const GET_ALL_DAILIES_BY_TAG_END = 'GET_ALL_DAILIES_BY_TAG_END';
export const GET_PUBLIC_DAILIES_BY_TAG_START =
  'GET_PUBLIC_DAILIES_BY_TAG_START';
export const GET_PUBLIC_DAILIES_BY_TAG_END = 'GET_PUBLIC_DAILIES_BY_TAG_END';
export const GET_PUBLIC_DAILIES_START = 'GET_PUBLIC_DAILIES_START';
export const GET_PUBLIC_DAILIES_END = 'GET_PUBLIC_DAILIES_END';
export const GET_DAILY_BY_ID_START = 'GET_DAILY_BY_ID_START';
export const GET_DAILY_BY_ID_END = 'GET_DAILY_BY_ID_END';
export const DELETE_DAILY_START = 'DELETE_DAILY_START';
export const DELETE_DAILY_END = 'DELETE_DAILY_END';
export const ADD_DAILY_COMMENT_START = 'ADD_DAILY_COMMENT_START';
export const ADD_DAILY_COMMENT_END = 'ADD_DAILY_COMMENT_END';
export const DELETE_DAILY_COMMENT_START = 'DELETE_DAILY_COMMENT_START';
export const DELETE_DAILY_COMMENT_END = 'DELETE_DAILY_COMMENT_END';
export const STAR_DAILY_START = 'STAR_DAILY_START';
export const STAR_DAILY_END = 'STAR_DAILY_END';
