export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_ONE_ERROR = 'CLEAR_ONE_ERROR';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const SET_USER = 'SET_USER';
export const UNSET_USER = 'UNSET_USER';
export const GET_PUBLIC_DAILIES_START = 'GET_PUBLIC_DAILIES_START';
export const GET_ALL_DAILIES_END = 'GET_ALL_DAILIES_END';
export const MANIPULATE_DAILY_START = 'MANIPULATE_DAILY_START';
export const MANIPULATE_DAILY_END = 'MANIPULATE_DAILY_END';
